spring:
  cloud:
    gateway:
      routes:
        - id: my-test
          uri: http://localhost:2020
          predicates:
            - Path=/**
          filters:
            - name: CachingBodyFilter
            - name: ReadBodyFilter
            - name: AuthenticationFilter
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    web: debug