spring:
  cloud:
    gateway:
      routes:
        - id: my-test
          uri: http://localhost:9090
          predicates:
            - Path=/**
          filters:
            - name: CachingBodyFilter
            - name: ReadBodyFilter