spring:
  cloud:
    gateway:
      routes:
        - id: my-test
          uri: http://localhost:2020
          predicates:
            - Path=/**
          filters:
            - name: CachingBodyFilter
            - name: ReadBodyFilter
            - name: AuthenticationFilter
  data.redis.database: 0
  data.redis.host: localhost
  data.redis.port: 6379

logging:
  structured:
    format:
      console: com.giri.springcloudgateway.global.logging.JsonLogger
  level:
    web: debug
    reactor.netty.http.client: debug